import{A as q,i as c,S as $}from"./assets/vendor-cf73e4e9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();function T({webformatURL:t,largeImageURL:o,tags:i,likes:s,views:e,comments:r,downloads:n}){return`<li class="liElem"><a href="${o}">
        <img src=${t} alt=${i} data-source=${o}/></a>
        <div>
            <p>likes: <span>${s}</span></p>
            <p>views: <span>${e}</span></p>
            <p>comments: <span>${r}</span></p>
            <p>downloads: <span>${n}</span></p>
        </div>
    </li>`}function g(t){return t.map(T).join("")}async function v(t,o){const i=q.create({baseURL:"https://pixabay.com/api/",params:{key:"44428338-9196df2338f39a1a95b2ab25e",image_type:"photo",orientation:"horizontal",q:`${t}`,safesearch:!0,per_page:15,page:o}});try{return(await i.get("")).data}catch(s){console.log(s)}}const l=document.querySelector(".form-el"),y=l.querySelector(".input-search"),L=document.querySelector(".loader"),m=document.querySelector(".img-list"),f=document.querySelector(".load");let a=1;const x=15;let u=1,d="";l.addEventListener("submit",t=>{t.preventDefault(),m.innerHTML="",y.value.trim()===""&&c.error({title:"Error",message:"Enter your details. Please try again!",position:"topRight"}),d=y.value.trim(),a=1,E(),h(),M(d,a),l.reset()});f.addEventListener("click",()=>{a++,E(),h(),O(d,a)});async function O(t,o){try{const i=await v(t,o);i.total===0&&S();const s=g(i.hits);m.insertAdjacentHTML("beforeend",s),b(),B()}catch{P()}w(),p()}function A(){f.classList.remove("visually-hidden")}function h(){f.classList.add("visually-hidden")}function B(){const t=document.querySelectorAll(".liElem");if(t.length>0){const o=t[0].getBoundingClientRect().height;window.scrollBy({top:o*2,left:0,behavior:"smooth"})}}async function M(t,o){try{const i=await v(t,o);u=Math.ceil(i.total/x),i.total===0&&(p(),S());const s=g(i.hits);m.insertAdjacentHTML("beforeend",s),b()}catch{P()}w(),p()}function w(){a>=u?(h(),u&&c.info({message:"We're sorry, but you've reached the end of search results."})):A()}function b(){new $(".img-list a",{overlayOpacity:.9,captionDelay:250,captionsData:"alt"}).refresh()}function p(){L.classList.add("visually-hidden")}function E(){L.classList.remove("visually-hidden")}function S(){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}function P(){c.warning({message:"Problem with server!",position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
