import{A as v,i as p,S as L}from"./assets/vendor-cf73e4e9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const m=15;let c=1;async function b(t,o){const s=v.create({baseURL:"https://pixabay.com/api/",params:{key:"44428338-9196df2338f39a1a95b2ab25e",image_type:"photo",orientation:"horizontal",q:`${t}`,safesearch:!0,per_page:m,page:o}});try{const{data:i}=await s.get("");return c=i.totalHits/m,o>=c&&(c&&p.info({message:"We're sorry, but you've reached the end of search results."}),l()),i.hits}catch(i){console.log(i)}}const S=document.querySelector(".img-list");async function f(t,o){try{const s=await b(t,o);if(s&&s.length>0){const i=E(s);S.insertAdjacentHTML("beforeend",i),q()}else p.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}catch(s){console.log(s)}}function w({webformatURL:t,largeImageURL:o,tags:s,likes:i,views:e,comments:r,downloads:n}){return`<li class="liElem"><a href="${o}">
        <img src=${t} alt=${s} data-source=${o}/></a>
        <div>
            <p>likes: <span>${i}</span></p>
            <p>views: <span>${e}</span></p>
            <p>comments: <span>${r}</span></p>
            <p>downloads: <span>${n}</span></p>
        </div>
    </li>`}function E(t){return t.map(w).join("")}function q(){new L(".img-list a",{overlayOpacity:.9,captionDelay:250,captionsData:"alt"}).refresh()}const h=document.querySelector(".form-el"),u=h.querySelector(".input-search"),y=document.querySelector(".loader"),$=document.querySelector(".img-list"),d=document.querySelector(".load");let a=1;h.addEventListener("submit",t=>{if(t.preventDefault(),$.innerHTML="",a=1,l(),u.value.trim()===""){l();return}else f(u.value.trim(),a),g();y.classList.add("visually-hidden")});d.addEventListener("click",()=>{a++,l(),x()});function x(){f(u.value.trim(),a).then(()=>{O(),g()}),y.classList.add("visually-hidden")}function g(){d.classList.remove("visually-hidden")}function l(){d.classList.add("visually-hidden")}function O(){const t=document.querySelectorAll(".liElem");if(t.length>0){const o=t[0].getBoundingClientRect().height;window.scrollBy({top:o*2,left:0,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
